dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    secure: osLH5mAvGZm0+ELjX3fFK9OXsB16c5udK6dHvNFO3tkkYQpEZQWTjXues4apQvdJsepWsiqf4YQ5qM7jGdabR+AFafUIXbyKZZY1KqcUBN8/bRxMjt5HdyX5s4s1/dd45mWpxFaw/1C/j6LCXQhdvbtVh54cQZ6mhNvbAfnGjWrePN/evarmSVbzjksZgpnZHbGfeNJ+9QobDwtFN+9ckazD4JyzmtigsFPfRO2D1eWDQxtgJrYExkIwSgC602Suhm7wgbyKwlnX3FzxBbS2fkA486GrBRQutK6VN+sgKk9FA0UIXDIeyIyYq3IvGKvuGKFBiQ8wLaXEN6XPkZ3nrZ1cn03BASlr+o0BcED2uMtXS/yVA/34X7YZtZedLxHB+6lwx2Rguk2BW+2BImVvSaxZOwA74uOcdWWkFB+8JkJQ922lSiJOTFJoFgkH4W06oEjdgHJY4s1pRH/HCXeqcXKcvxjuQjoKGUXeoyYE12Ybqz9MWbUK2AdHr3OXOKBR1qodcVjSasNy7VhdqN+Rd8HwezIrpC9CyoxIGy94QNMgijn3IkRgCj+Pu1fTxvcjQJfvfFxIlflSb6lxs87hxi3bUqSnni0BxcecRPwfwlZ5U12HsCyKVhUcuiVBvHHpi/xTvRSlpMBatTKrAB2mCNrDeJA008jOXYTJWaVzU9c=
