dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: XKkOjrV+lULN0KHBsIZCtkQfGhI4YO+npULdYJqAxzvD0opneKf6SffIRQZn3gb9DCZxo+kQo6DPywE3geosHVNsdsoxEtqbzhnW6LShcXKXvQSCZmJDCxPahw61wfqcwilgZBN2sWqaxCGYtm4o8weRE1P462gzsK4efb33veD7zlK7UUMmTfapbBWunkzu2iRdhLlgh5EXRaEDLsnGu7COHZjQ8s0BtRxuIfSKqgWynvPQaKzrqFmWCoeahU+xxN8ZaXY3x2x9uz/ozdMlVdvon/W0wvyU+Nda/CFo7g8IAvJoGZFLDDWjkmaRhsw6hsGyxidqDmNKBVBkv+NGZA1QMWuOxYrfrIrwWN9UzIAA2d7fk5qyFfMTvbuhtfRLsGN4IME3rmpEJBdfooSxdKyWyoHmo4P+xjzjsbyQAIvwWjnfv2ByOBFYiZ2lfhCeZHFOT5p7EONNlIwGj+9TJTnndMHzQyAU1t1Mfsl0fI3xARnMzVBAg2Da6cJ29vpN10hU16k304rSckkDeIpzsnYISliqM0TiEb7YUQ4y50HP1BAag33sYDnW73Z5X6HyyQE8Nk611Drkqemc8EvPmJf2cRxxBvCrmcqlrzYfwu+yOd0HJea5fcNhqsjkyT6ebo28hg+r58GRK9buUR+PPu4Vjt8gncXaZz6pc1uMc1s=
