dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    secure: EFVD2ypHzk2MvKO6C4Ldwo4cFmjipif+UcwjO7gLfPqavNSOsvOY7qkyT3C4wdryxkJyI0byagMSTCDO1ckVJzixQsoJh4XNInr/dQEbh5nok53C4ISQ+6UyhLsu5fz3yOwae9VDhtFnFhan+CgzwgtKLZwPWmMoC0dPVTokFTQmTzA3l2BUPhmjiH9HowiZk7gqSLS622I9Je9SA4fX9LY3df5WBVGd0kF7vGtiRwQbfEjZxlc9nOSdZQV69e1UDxIYRhM/GifM+vAQiwGO1VOIFUl7xpPyalSCY0nSH+0sm/P+6k5o35F4sTqi28Y5ES8X/6YO0PidOFoKasOvUhghTJQms2pCNewaqUNUEu2cdlJIuR/tKzeEZDgN1KeDIZX+0MEpjD1m7wyXYULY0yb42MGqjyAnLLOiwjrsFYn0rGLFjzM1OZmPlx/mJyVBpsWVp0XEcO2gX5BU3RPioQC7jrE44ByJzUXHkvmr/8xVUtA0vm25idP0x0Lmbf233Fn2VDPNDU20+WCiKpxfxR3Weu2Ep79iC71yU7wf4H4frJF4nVHSOI+MzrBITL1fBakb4EVVaWXrGOGS1O2FJqmoBKQ/14JsqIBM04azmXTo6diIP86uaxVX7RpFP/rqELzF0QCss5zqgLkjB7uMURQjW8sqBKpaZnye3YKNt4M=
